### ISSUE TITLE
Change how helper script works

### ISSUE THREAD

**Issue by Exiled1** [ChatImproVR/iteration0#19]
The helper script should look into the environment variable and append the `/target/wasm32-unknown-unknown/release` to the items within the environment variable. This would reduce the amount of boilerplate stuff the user would need to do.

Also we should consider making a helper script for adding your folder to the env variable. Something that gets shipped with the template.

Usage would be: `./helper $(pwd)` and it would add that. Or something along those lines.

**Comment by MrKangs** [comment]
I believe this issue has been resolve with recent pushed regarding this issue; hence, I am going to close this issue unless there is additional feature that needs to implement.
