### ISSUE TITLE
Replace `for key in ...` with `for entity in ...`

### ISSUE THREAD

**Issue by Masterchef365** [ChatImproVR/iteration0#54]
Query results used to have "keys" instead of entity IDs, now they don't. But this artifact is left behind and it's a little misleading. Fix me!

**Comment by MrKangs** [comment]
Do you want someone to update the syntax of all the example plugins from the word "key" to "entity" or something similar that is not misleading? What are some other changes you are looking at for this issue particularly?

**Comment by Masterchef365** [comment]
> Do you want someone to update the syntax of all the example plugins from the word "key" to "entity"

ye

**Comment by Masterchef365** [comment]
Resolved by #55
